sonar.projectKey=huzaifa678_billing-service
sonar.organization=huzaifa678
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.java.binaries=billing-domain/build/classes,billing-application/build/classes,billing-adapters/build/classes,billing-bootstrap/build/classes
sonar.sources=billing-domain/src/main/java,billing-application/src/main/java,billing-adapters/src/main/java,billing-bootstrap/src/main/java
sonar.tests=billing-domain/src/test/java,billing-application/src/test/java,billing-adapters/src/test/java,billing-bootstrap/src/test/java
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml