sonar.projectKey=billing-service
sonar.host.url=http://sonarqube:9000
sonar.token=${env.SONAR_TOKEN}

sonar.sourceEncoding=UTF-8

sonar.java.binaries=build/classes

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml