name: billing-service CD

on:
  push:
    branches: [test, main]
    paths: [billing-service/**]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set environment
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "test" ]]; then
            echo "file=values-test.yaml" >> $GITHUB_OUTPUT
            echo "env=test" >> $GITHUB_OUTPUT
          else
            echo "file=values-prod.yaml" >> $GITHUB_OUTPUT
            echo "env=prod" >> $GITHUB_OUTPUT
          fi

      - name: update ArgoCD values-prod.yaml
        env:
          ARGOCD_REPO_TOKEN: ${{ secrets.ARGOCD_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${ARGOCD_REPO_TOKEN}@github.com/huzaifa678/SAAS-Continious-Delivery.git /tmp/cd
          cd /tmp/cd

          wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          chmod +x /usr/local/bin/yq

          yq -i '.billingService.image.repository = "${{ steps.ecr.outputs.url }}"' saas-chart/values-prod.yaml
          yq -i '.billingService.image.tag        = "${{ github.sha }}"'             saas-chart/values-prod.yaml

          git config user.email "ci@github.com"
          git config user.name  "GitHub Actions"
          git add saas-chart/values-prod.yaml
          git commit -m "cd(billing-service): update image to ${{ github.sha }}"
          git push
